spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: film-service
          uri: lb://film-service
          predicates:
            - Path=/api/v*/auth*,/api/v*/auth/*,/api/v*/cinemas*,/api/v*/cinemas/*,/api/v*/films*,/api/v*/films/*,/api/v*/film-lists*,/api/v*/film-lists/*,/api/v*/actors*,/api/v*/actors/*,/api/v*/directors*,/api/v*/directors/*

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

